from __future__ import annotations


HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PhonoWeave — Live Calibration</title>
<style>
:root{--bg:#d8d9d5;--chrome:#ecece8;--line:#9fa19d;--line2:#c4c5c1;--ink:#171816;--muted:#5d605b;--sel:#1d4f91;--ok:#24653f;--warn:#8a5b00;--danger:#8d2f2f;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:#f4f4f1;color:var(--ink);font:13px/1.35 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}.app{height:100%;display:grid;grid-template-rows:32px 42px 1fr 25px}.menubar,.toolbar,.statusbar{border-color:var(--line);background:var(--chrome)}.menubar{display:flex;align-items:center;border-bottom:1px solid var(--line);padding:0 8px;gap:18px;font-size:12px}.brand{font-weight:700;letter-spacing:.3px}.spacer{flex:1}.back{color:inherit;text-decoration:none}.lang button,.toolbtn{font:inherit;border:1px solid #7f817c;background:#fff;height:27px;padding:3px 9px;cursor:pointer}.lang button.active{background:#2c2d2a;color:#fff}.toolbar{display:flex;align-items:center;gap:7px;padding:6px 8px;border-bottom:1px solid var(--line)}.toolbtn.primary{background:#30322f;color:#fff}.toolbtn:disabled{opacity:.45;pointer-events:none}.session{margin-left:auto;font:10px var(--mono);color:var(--muted)}
.workspace{min-height:0;display:grid;grid-template-columns:235px 1fr 310px}.pane{min-width:0;min-height:0;border-right:1px solid var(--line);display:grid;grid-template-rows:27px 1fr}.pane:last-child{border-right:0}.panehead{display:flex;align-items:center;padding:0 8px;background:#dadbd7;border-bottom:1px solid var(--line);font-size:10px;text-transform:uppercase;letter-spacing:.8px;font-weight:700}.panehead span:last-child{margin-left:auto;font-family:var(--mono);font-weight:400}.list{overflow:auto;background:#e9eae6}.item{display:grid;grid-template-columns:34px 1fr 24px;padding:5px 8px;border-bottom:1px solid #d2d3cf;cursor:pointer}.item:hover{background:#dddeda}.item.selected{background:var(--sel);color:#fff}.item.done .state{color:var(--ok)}.base{font:bold 12px var(--mono)}.ctx{font-size:10px;color:#666}.item.selected .ctx{color:#e0e8f4}.state{text-align:right;font:11px var(--mono)}
.stage{display:grid;grid-template-rows:1fr auto;background:#fff}.promptarea{display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px}.promptmeta{font:11px var(--mono);color:var(--muted);margin-bottom:20px}.pattern{font:700 38px/1.3 var(--mono);letter-spacing:1px;text-align:center}.token{padding:3px 5px;border-bottom:3px solid transparent}.token.hot{background:#e6edf7;border-bottom-color:var(--sel)}.beat{margin-top:26px;font:12px var(--mono);color:var(--muted)}.progressbar{height:4px;background:#dedfdb;width:min(560px,80%);margin-top:10px}.progress{height:100%;background:#555;width:0%}.controls{display:flex;align-items:center;justify-content:center;gap:7px;padding:10px;border-top:1px solid var(--line);background:#ecece8}.controls button{font:inherit;border:1px solid #7f817c;background:#fff;height:29px;padding:4px 12px}.controls .record{background:#30322f;color:#fff}.controls button:disabled{opacity:.45}.recording{color:var(--danger);font:11px var(--mono);min-width:90px}
.help{overflow:auto;background:#f3f3ef;padding:12px}.help h3{font-size:10px;text-transform:uppercase;letter-spacing:.8px;margin:10px 0 6px}.help p{margin:0 0 8px;line-height:1.55}.kv{display:grid;grid-template-columns:105px 1fr;border-top:1px solid #ccc}.kv div{padding:5px 3px;border-bottom:1px solid #ccc}.k{color:var(--muted)}.mono{font-family:var(--mono);font-size:11px}.caution{border-left:3px solid var(--warn);padding-left:8px;color:#555}.statusbar{display:flex;align-items:center;border-top:1px solid var(--line);padding:0 8px;font:10px var(--mono);color:#464844}.statusbar .spacer{flex:1}.error{color:var(--danger)}
</style>
</head>
<body><div class="app">
<div class="menubar"><span class="brand">PHONOWEAVE</span><a class="back" href="/">Workbench</a><span>LIVE CALIBRATION</span><span class="spacer"></span><div class="lang"><button id="zh">中文</button><button id="en">EN</button></div></div>
<div class="toolbar"><button class="toolbtn primary" id="start"></button><button class="toolbtn" id="mic"></button><button class="toolbtn" id="record" disabled></button><button class="toolbtn" id="retry" disabled></button><button class="toolbtn" id="next" disabled></button><span class="session" id="session">—</span></div>
<div class="workspace">
<section class="pane"><div class="panehead"><span id="prompts-title"></span><span id="count">0/0</span></div><div class="list" id="list"></div></section>
<section class="pane"><div class="panehead"><span id="elicitation-title"></span><span id="index-label">—</span></div><div class="stage"><div class="promptarea"><div class="promptmeta" id="meta"></div><div class="pattern" id="pattern">—</div><div class="beat" id="beat"></div><div class="progressbar"><div class="progress" id="progress"></div></div></div><div class="controls"><button class="record" id="record2" disabled></button><span class="recording" id="recording"></span></div></div></section>
<section class="pane"><div class="panehead"><span id="protocol-title"></span></div><div class="help"><h3 id="what-title"></h3><p id="what"></p><h3 id="current-title"></h3><div class="kv"><div class="k" id="target-k"></div><div class="mono" id="target">—</div><div class="k" id="family-k"></div><div class="mono" id="family">—</div><div class="k" id="repeats-k"></div><div class="mono" id="repeats">—</div><div class="k" id="tempo-k"></div><div class="mono">72 BPM</div></div><h3 id="method-title"></h3><p class="caution" id="method"></p></div></section>
</div>
<div class="statusbar"><span id="status"></span><span class="spacer"></span><span id="saved"></span></div>
</div>
<script>
const $=id=>document.getElementById(id);let lang=localStorage.getItem('phonoweave.language')||'zh';let protocol=null,session=null,index=0,stream=null,ctx=null,source=null,processor=null,chunks=[],sampleRate=0,busy=false,done=new Set();
const T={zh:{start:'新建校准会话',mic:'启用麦克风',record:'按节拍录制',retry:'重录本项',next:'下一项',prompts:'固定提示集',elicitation:'录音提示',protocol:'协议',whatTitle:'这是什么',what:'这不是声库补录，也不会验证 LynnSu。它用冻结的提示词测试当前说话人的语境发音差异，并为后续生成个人化 synthesis inventory 提供受控录音。',current:'当前项目',target:'目标',family:'语境',repeats:'重复',tempo:'节拍',methodTitle:'方法边界',method:'v0.1 只负责固定提示与受控采集。自动声学判定尚未接入，因此录完不会直接宣称某个音需要拆分。',ready:'创建会话并允许麦克风后即可开始。',starting:'正在创建校准会话…',micReady:'麦克风已启用。',micFail:'无法使用麦克风：',recording:'● REC',saved:'已保存',complete:'固定提示集已全部录完。'},en:{start:'New calibration session',mic:'Enable microphone',record:'Record to beat',retry:'Redo item',next:'Next',prompts:'Frozen prompts',elicitation:'Elicitation',protocol:'Protocol',whatTitle:'What this is',what:'This is not a voicebank supplement and does not validate LynnSu. It uses a frozen prompt set to collect controlled context-conditioned speech from the current speaker.',current:'Current item',target:'Target',family:'Context',repeats:'Repeats',tempo:'Tempo',methodTitle:'Method boundary',method:'v0.1 performs frozen elicitation and controlled recording only. Automatic acoustic decisions are not connected yet, so recording does not itself imply a split.',ready:'Create a session and enable the microphone to begin.',starting:'Creating calibration session…',micReady:'Microphone enabled.',micFail:'Could not use microphone: ',recording:'● REC',saved:'saved',complete:'Frozen prompt set complete.'}};
function t(k){return T[lang][k]}function apply(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';localStorage.setItem('phonoweave.language',lang);$('zh').classList.toggle('active',lang==='zh');$('en').classList.toggle('active',lang==='en');[['start','start'],['mic','mic'],['record','record'],['record2','record'],['retry','retry'],['next','next'],['prompts-title','prompts'],['elicitation-title','elicitation'],['protocol-title','protocol'],['what-title','whatTitle'],['what','what'],['current-title','current'],['target-k','target'],['family-k','family'],['repeats-k','repeats'],['tempo-k','tempo'],['method-title','methodTitle'],['method','method']].forEach(([id,k])=>$(id).textContent=t(k));if(!session)setStatus(t('ready'));render()}
function setStatus(s,e=false){$('status').textContent=s;$('status').classList.toggle('error',e)}
function currentPrompt(){return protocol?.prompts[index]||null}
function render(){if(!protocol){$('list').innerHTML='';return}let h='';protocol.prompts.forEach((p,i)=>{h+=`<div class="item ${i===index?'selected':''} ${done.has(i)?'done':''}" data-i="${i}"><span class="base">${p.base_unit}</span><span><div>${p.spoken_pattern}</div><div class="ctx">${p.context_family}</div></span><span class="state">${done.has(i)?'✓':''}</span></div>`});$('list').innerHTML=h;document.querySelectorAll('.item').forEach(x=>x.onclick=()=>{if(!busy){index=Number(x.dataset.i);render()}});$('count').textContent=`${done.size}/${protocol.prompts.length}`;const p=currentPrompt();if(!p)return;$('index-label').textContent=`${String(index+1).padStart(2,'0')} / ${protocol.prompts.length}`;$('meta').textContent=`${p.base_unit} · ${p.context_family} · ${p.role_scope}`;$('pattern').innerHTML=p.tokens.map((x,i)=>`<span class="token" data-token="${i}">${x}</span>`).join(' ');$('target').textContent=p.syllable;$('family').textContent=p.context_family;$('repeats').textContent=p.repeats;$('record').disabled=!session||!stream||busy;$('record2').disabled=$('record').disabled;$('retry').disabled=!done.has(index)||busy;$('next').disabled=busy||index>=protocol.prompts.length-1}
async function startSession(){setStatus(t('starting'));const r=await fetch('/api/calibration/start',{method:'POST'}),d=await r.json();if(!r.ok){setStatus(d.error||'error',true);return}protocol=d.protocol;session=d.session_id;index=0;done.clear();$('session').textContent=`${session} · ${d.session_dir}`;setStatus(t('ready'));render()}
async function enableMic(){try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});setStatus(t('micReady'));render()}catch(e){setStatus(t('micFail')+e.message,true)}}
function beginCapture(){ctx=new (window.AudioContext||window.webkitAudioContext)();sampleRate=ctx.sampleRate;source=ctx.createMediaStreamSource(stream);processor=ctx.createScriptProcessor(4096,1,1);chunks=[];processor.onaudioprocess=e=>chunks.push(new Float32Array(e.inputBuffer.getChannelData(0)));source.connect(processor);processor.connect(ctx.destination)}
async function endCapture(){processor.disconnect();source.disconnect();await ctx.close();let n=chunks.reduce((a,x)=>a+x.length,0),samples=new Float32Array(n),o=0;for(const x of chunks){samples.set(x,o);o+=x.length}return encodeWav(samples,sampleRate)}
function encodeWav(samples,sr){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b);function s(o,x){for(let i=0;i<x.length;i++)v.setUint8(o+i,x.charCodeAt(i))}s(0,'RIFF');v.setUint32(4,36+samples.length*2,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,samples.length*2,true);let o=44;for(let i=0;i<samples.length;i++,o+=2){let x=Math.max(-1,Math.min(1,samples[i]));v.setInt16(o,x<0?x*32768:x*32767,true)}return b}
function beep(accent=false){const a=new (window.AudioContext||window.webkitAudioContext)(),osc=a.createOscillator(),g=a.createGain();osc.frequency.value=accent?1000:700;g.gain.value=.045;osc.connect(g);g.connect(a.destination);osc.start();osc.stop(a.currentTime+.07);osc.onended=()=>a.close()}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
async function recordCurrent(){if(busy||!session||!stream)return;busy=true;render();$('recording').textContent=t('recording');const p=currentPrompt(),beatMs=60000/72;beginCapture();await sleep(300);let total=p.repeats*p.tokens.length;beep(true);await sleep(beatMs);let step=0;for(let rep=0;rep<p.repeats;rep++){for(let ti=0;ti<p.tokens.length;ti++){document.querySelectorAll('.token').forEach((x,i)=>x.classList.toggle('hot',i===ti));beep(ti===0);step++;$('beat').textContent=`${rep+1}/${p.repeats} · ${ti+1}/${p.tokens.length}`;$('progress').style.width=`${step/total*100}%`;await sleep(beatMs)}}document.querySelectorAll('.token').forEach(x=>x.classList.remove('hot'));beep(true);await sleep(beatMs);const wav=await endCapture();const r=await fetch(`/api/calibration/recording?index=${index}&sample_rate=${sampleRate}`,{method:'POST',headers:{'Content-Type':'audio/wav'},body:wav}),d=await r.json();if(r.ok){done.add(index);$('saved').textContent=`${t('saved')}: ${d.saved}`;if(index<protocol.prompts.length-1)index++;else setStatus(t('complete'))}else setStatus(d.error||'save failed',true);$('recording').textContent='';$('beat').textContent='';$('progress').style.width='0%';busy=false;render()}
$('start').onclick=startSession;$('mic').onclick=enableMic;$('record').onclick=recordCurrent;$('record2').onclick=recordCurrent;$('retry').onclick=recordCurrent;$('next').onclick=()=>{if(index<protocol.prompts.length-1){index++;render()}};$('zh').onclick=()=>{lang='zh';apply()};$('en').onclick=()=>{lang='en';apply()};apply();
</script></body></html>"""
