from __future__ import annotations


HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PhonoWeave — Workbench</title>
<style>
:root{--bg:#d8d9d5;--chrome:#ecece8;--line:#9fa19d;--line2:#c4c5c1;--ink:#171816;--muted:#5d605b;--sel:#1d4f91;--seltext:#fff;--ok:#24653f;--warn:#8a5b00;--danger:#8d2f2f;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
*{box-sizing:border-box}html,body{height:100%}body{margin:0;background:var(--bg);color:var(--ink);font:13px/1.35 -apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif;overflow:hidden}button,input{font:inherit;color:inherit}
.app{height:100%;display:grid;grid-template-rows:32px 43px 1fr 25px}.menubar{display:flex;align-items:center;border-bottom:1px solid var(--line);background:#f5f5f1;padding:0 8px;gap:18px;font-size:12px}.brand{font-weight:700;letter-spacing:.3px}.menuitem{color:#30312f}.spacer{flex:1}.lang{display:flex;gap:1px;border:1px solid var(--line);background:#fff}.lang button{border:0;background:transparent;padding:2px 7px;font-size:11px}.lang button.active{background:#2c2d2a;color:#fff}
.toolbar{display:grid;grid-template-columns:auto minmax(240px,1fr) auto auto auto auto auto;align-items:center;gap:6px;padding:6px 8px;background:var(--chrome);border-bottom:1px solid var(--line)}.toolbar label{font-size:11px;color:var(--muted);text-transform:uppercase;letter-spacing:.7px}.toolbar input{height:27px;border:1px solid var(--line);background:#fff;padding:3px 7px;outline:none;font-family:var(--mono);font-size:11px}.toolbtn,.exportbtn{height:27px;border:1px solid #7f817c;background:linear-gradient(#fff,#dcded9);padding:3px 9px;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;white-space:nowrap}.toolbtn:active,.exportbtn:active{background:#d0d1cd}.toolbtn.primary{background:#30322f;color:#fff;border-color:#222}.toolbtn:disabled,.exportbtn.disabled{opacity:.45;pointer-events:none}
.workbench{min-height:0;display:grid;grid-template-columns:210px minmax(420px,1fr) 390px;background:#fff}.pane{min-width:0;min-height:0;border-right:1px solid var(--line);display:grid;grid-template-rows:26px 1fr;background:#f8f8f5}.pane:last-child{border-right:0}.panehead{height:26px;display:flex;align-items:center;padding:0 8px;border-bottom:1px solid var(--line);background:#dadbd7;font-size:11px;text-transform:uppercase;letter-spacing:.75px;font-weight:700}.panehead .count{margin-left:auto;font-family:var(--mono);font-weight:400;color:var(--muted)}
.sidebar{overflow:auto;padding:4px 0;background:#e9eae6}.sidegroup-title{padding:5px 8px 3px;color:#555;font-size:10px;text-transform:uppercase;letter-spacing:.8px}.sideitem{display:grid;grid-template-columns:34px 1fr 15px;align-items:center;height:25px;padding:0 8px 0 12px;cursor:pointer}.sideitem:hover{background:#dddeda}.sideitem.selected{background:var(--sel);color:var(--seltext)}.symbol{font-family:var(--mono);font-weight:700}.dot{width:7px;height:7px;border-radius:50%;justify-self:end;background:#777}.dot.split_recommended,.dot.three_realizations_provisional{background:#2d8d51}.dot.unresolved{background:#c38a16}.dot.merge_supported{background:#666}
.tablewrap{overflow:auto;background:#fff}.grid{border-collapse:collapse;width:100%;table-layout:fixed;font-size:12px}.grid th{position:sticky;top:0;z-index:2;background:#e4e5e1;border-bottom:1px solid var(--line);border-right:1px solid var(--line2);text-align:left;padding:5px 6px;height:25px;font-size:10px;text-transform:uppercase;letter-spacing:.55px}.grid td{height:25px;padding:3px 6px;border-bottom:1px solid #dedfdb;border-right:1px solid #eeeeea;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.grid tbody tr:nth-child(even){background:#fafaf8}.grid tbody tr:hover{background:#edf1f6}.grid tbody tr.selected{background:#d8e5f5}.rawcode{font-family:var(--mono);font-size:10px;color:#555}.decision-mark{font-weight:700}.decision-mark.split_recommended,.decision-mark.three_realizations_provisional{color:var(--ok)}.decision-mark.unresolved{color:var(--warn)}
.inspector{overflow:auto;background:#f3f3ef}.inspector-empty{padding:18px;color:var(--muted)}.inspector-inner{padding:0 10px 16px}.phoneme-title{display:flex;align-items:baseline;gap:10px;padding:12px 0 8px;border-bottom:1px solid var(--line)}.phoneme-title .big{font:700 32px/1 var(--mono)}.phoneme-title .type{color:var(--muted)}.section{padding:10px 0;border-bottom:1px solid var(--line2)}.section:last-child{border-bottom:0}.section h3{margin:0 0 7px;font-size:10px;text-transform:uppercase;letter-spacing:.8px}.kv{display:grid;grid-template-columns:122px 1fr;border-top:1px solid #d0d1cd}.kv>div{padding:5px 4px;border-bottom:1px solid #d0d1cd}.kv .k{color:var(--muted)}.value-main{font-weight:600}.value-raw{font:10px/1.3 var(--mono);color:#6b6d68;margin-top:2px}.explain{font-size:12px;line-height:1.5}.caution{margin-top:6px;color:var(--muted);font-size:11px}.groups,.diag{font-family:var(--mono);font-size:11px}.grouprow,.diagrow{padding:5px 4px;border-top:1px solid #d0d1cd}.context{color:var(--muted);font-family:inherit}.notes{font:10px/1.45 var(--mono);white-space:pre-wrap;color:#565853;margin:0}.gaphead{display:flex;align-items:center;gap:8px}.priority{font:10px/1 var(--mono);padding:2px 4px;border:1px solid var(--line);background:#fff}.priority.high{color:var(--danger);border-color:#b99}.priority.medium{color:var(--warn);border-color:#ba9}.action{font-weight:700}.recline{margin-top:2px;color:#555}.reason{font:10px/1.4 var(--mono);padding:2px 0;color:#555}
.statusbar{display:grid;grid-template-columns:minmax(200px,1fr) auto auto auto auto auto;align-items:center;gap:15px;padding:0 8px;background:#d4d5d1;border-top:1px solid var(--line);font:10px/1 var(--mono);color:#464844}.statusmsg.error{color:var(--danger)}.stat strong{color:#111}.idle{padding:18px;color:#747670;font-style:italic}.spinner{display:inline-block;width:10px;height:10px;border:1px solid #888;border-top-color:transparent;border-radius:50%;animation:spin .7s linear infinite;margin-right:5px}@keyframes spin{to{transform:rotate(360deg)}}
@media(max-width:1050px){.workbench{grid-template-columns:170px 1fr}.pane.inspector-pane{display:none}.toolbar{grid-template-columns:auto 1fr auto auto}.exportbtn{display:none}}
</style>
</head>
<body>
<div class="app">
  <div class="menubar"><span class="brand">PHONOWEAVE</span><span class="menuitem" id="project-label"></span><span class="menuitem" id="analysis-label"></span><span class="menuitem" id="export-label"></span><span class="spacer"></span><div class="lang"><button id="lang-zh">中文</button><button id="lang-en">EN</button></div></div>
  <div class="toolbar"><label id="voicebank-label" for="voicebank"></label><input id="voicebank" placeholder="/Users/.../OpenUtau/Singers/Voicebank"><button class="toolbtn" id="browse"></button><button class="toolbtn primary" id="analyze"></button><a class="exportbtn disabled" id="profile" href="/api/export/profile"></a><a class="exportbtn disabled" id="inventory" href="/api/export/inventory"></a><a class="exportbtn disabled" id="supplement" href="/api/export/supplement-reclist"></a></div>
  <div class="workbench">
    <section class="pane"><div class="panehead"><span id="inventory-title"></span><span class="count" id="inventory-count">0</span></div><div class="sidebar" id="sidebar"><div class="idle" id="sidebar-idle"></div></div></section>
    <section class="pane"><div class="panehead"><span id="matrix-title"></span><span class="count" id="matrix-count">—</span></div><div class="tablewrap" id="table-wrap"><div class="idle" id="table-idle"></div></div></section>
    <section class="pane inspector-pane"><div class="panehead"><span id="inspector-title"></span></div><div class="inspector" id="inspector"><div class="inspector-empty" id="inspector-idle"></div></div></section>
  </div>
  <div class="statusbar"><div class="statusmsg" id="status"></div><div class="stat"><span id="onsets-label"></span> <strong id="onsets">—</strong></div><div class="stat"><span id="units-label"></span> <strong id="units">—</strong></div><div class="stat"><span id="unresolved-label"></span> <strong id="unresolved">—</strong></div><div class="stat"><span id="supplement-label"></span> <strong id="supplement-count">—</strong></div><div class="stat"><span id="unsupported-label"></span> <strong id="unsupported">—</strong></div></div>
</div>
<script>
let current=null,selected=null;const $=id=>document.getElementById(id);
const I18N={
 en:{project:'Project',analysis:'Analysis',export:'Export',voicebank:'Voicebank',browse:'Choose…',analyze:'Analyze',analyzing:'Analyzing',profile:'Profile YAML',inventoryExport:'Inventory YAML',supplementExport:'Supplement Reclist',inventory:'Inventory',matrix:'Analysis matrix',inspector:'Inspector',idleSide:'No voicebank loaded.',idleTable:'Open a voicebank and run analysis.',idleInspector:'Select an onset.',onset:'Onset',class:'Class',decision:'Decision',confidence:'Confidence',acoustic:'Acoustic',synthesis:'Synthesis',groups:'Realization groups',notes:'Raw analysis notes',interpretation:'Interpretation',evidence:'Evidence completion',gap:'Gap',priority:'Priority',next:'Next action',role:'Role scope',families:'Target contexts',diagnostics:'Diagnostic items',reason:'Why unresolved',onsets:'onsets',units:'units',unresolved:'unresolved',supplementItems:'supplement items',unsupported:'unsupported',choose:'Choose a voicebank.',opening:'Opening folder picker…',picked:'Voicebank selected.',canceled:'Selection canceled.',running:'Running full analysis…',failed:'Analysis failed.',done:(o,u)=>`${o} onsets / ${u} units`,caution:'Synthesis relevance is currently a signal-level proxy, not a perceptual listening result.',noGap:'No evidence-completion action is currently attached to this decision.'},
 zh:{project:'项目',analysis:'分析',export:'导出',voicebank:'声库',browse:'选择…',analyze:'分析',analyzing:'分析中',profile:'配置 YAML',inventoryExport:'库存 YAML',supplementExport:'补录表',inventory:'库存',matrix:'分析矩阵',inspector:'检查器',idleSide:'尚未载入声库。',idleTable:'选择声库并运行分析。',idleInspector:'选择一个声母查看。',onset:'声母',class:'类别',decision:'判断',confidence:'置信度',acoustic:'声学',synthesis:'合成',groups:'实现分组',notes:'原始分析记录',interpretation:'结果解释',evidence:'证据补全',gap:'证据缺口',priority:'优先级',next:'下一步',role:'位置范围',families:'目标语境',diagnostics:'诊断补录项',reason:'为什么暂不决定',onsets:'声母',units:'单元',unresolved:'暂不决定',supplementItems:'补录项',unsupported:'未支持',choose:'请选择一个声库。',opening:'正在打开文件夹选择器…',picked:'已选择声库。',canceled:'已取消选择。',running:'正在运行完整分析…',failed:'分析失败。',done:(o,u)=>`${o} 个声母 / ${u} 个单元`,caution:'合成相关性当前使用信号层代理指标，不等同于主观听感实验。',noGap:'当前判断没有附加的证据补全动作。'}};
const TERMS={class_name:{fricative:['Fricative','擦音'],affricate:['Affricate','塞擦音'],rhotic:['Rhotic','R 音 / 卷舌音'],lateral:['Lateral','边音'],nasal:['Nasal','鼻音'],stop:['Stop','塞音']},decision:{split_recommended:['Split recommended','建议区分录制'],unresolved:['Unresolved','暂不决定'],merge_supported:['Merge supported','支持合并'],three_realizations_provisional:['Three realizations, provisional','暂定三种实现']},confidence:{low:['Low','低'],moderate:['Moderate','中等'],high:['High','高']},acoustic:{weak_or_inconsistent:['Weak / inconsistent','较弱或不一致'],supported:['Supported','得到支持'],strongly_supported:['Strongly supported','得到强支持'],partial_coverage_limited:['Partial; coverage limited','部分支持；覆盖受限'],mixed:['Mixed','证据混合'],front_distinct_plain_rounded_mixed:['Front distinct; plain/rounded mixed','前化实现可区分；普通/圆唇证据混合']},synthesis:{not_tested:['Not tested','未测试'],supported_under_proxy:['Supported under proxy','当前代理指标支持'],split_not_supported_under_proxy:['Split not supported under proxy','当前代理指标未支持拆分'],unresolved:['Unresolved','暂不决定'],plain_rounded_split_supported_front_unresolved:['Plain/rounded split supported; front unresolved','普通/圆唇拆分支持；前化未定']},gap:{acoustic_inconclusive:['Acoustic evidence inconclusive','声学证据不足'],coverage_limited:['Coverage limited','覆盖不足'],synthesis_relevance:['Synthesis relevance unresolved','合成相关性待验证']},action:{supplemental_recording:['Supplemental recording','补充录音'],perceptual_validation:['Perceptual validation','听感验证']},priority:{high:['High','高'],medium:['Medium','中等']}};
const EXPLAIN={split_recommended:['Current acoustic and synthesis-relevance evidence supports separate context-conditioned synthesis realizations. This is not a claim of separate linguistic phonemes.','当前声学与合成相关性证据支持保留不同的语境合成实现。这并不表示它们一定是语言学上的独立音位。'],unresolved:['Evidence is insufficient for either a forced split or merge. The evidence-completion section below shows what is missing and what to do next.','证据不足以支持强制拆分或合并。下方“证据补全”会说明缺少什么，以及下一步该做什么。'],merge_supported:['Current evidence supports one shared synthesis realization across the tested contexts.','当前证据支持在已测试语境中共用一个合成实现。'],three_realizations_provisional:['Three context-conditioned realizations are provisionally retained under current coverage and proxy evidence.','在当前覆盖范围与代理指标下，暂时保留三种语境实现。']};
function initialLang(){const s=localStorage.getItem('phonoweave.language');if(s==='zh'||s==='en')return s;return navigator.language?.toLowerCase().startsWith('zh')?'zh':'en'}let lang=initialLang();
function t(k){return I18N[lang][k]}function term(g,v){const x=TERMS[g]?.[v];return x?(lang==='en'?x[0]:x[1]):v}function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function setStatus(s,e=false){$('status').textContent=s;$('status').classList.toggle('error',e)}
function applyLang(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';localStorage.setItem('phonoweave.language',lang);$('lang-zh').classList.toggle('active',lang==='zh');$('lang-en').classList.toggle('active',lang==='en');for(const [id,key] of [['project-label','project'],['analysis-label','analysis'],['export-label','export'],['voicebank-label','voicebank'],['browse','browse'],['analyze','analyze'],['profile','profile'],['inventory','inventoryExport'],['supplement','supplementExport'],['inventory-title','inventory'],['matrix-title','matrix'],['inspector-title','inspector'],['onsets-label','onsets'],['units-label','units'],['unresolved-label','unresolved'],['supplement-label','supplementItems'],['unsupported-label','unsupported']])$(id).textContent=t(key);if(!current){$('sidebar-idle').textContent=t('idleSide');$('table-idle').textContent=t('idleTable');$('inspector-idle').textContent=t('idleInspector');setStatus(t('choose'))}else{renderAll();setStatus(t('done')(current.summary.onsets,current.summary.synthesis_units))}}
function grouped(rows){const order=['stop','affricate','fricative','nasal','lateral','rhotic'];return order.map(k=>[k,rows.filter(r=>r.class_name===k)]).filter(x=>x[1].length)}
function renderSidebar(){let h='';for(const [group,rows] of grouped(current.rows)){h+=`<div class="sidegroup"><div class="sidegroup-title">${esc(term('class_name',group))}</div>`;for(const r of rows)h+=`<div class="sideitem ${r.base_unit===selected?'selected':''}" data-base="${esc(r.base_unit)}"><span class="symbol">${esc(r.base_unit)}</span><span>${esc(term('decision',r.decision))}</span><span class="dot ${esc(r.decision)}"></span></div>`;h+='</div>'}$('sidebar').innerHTML=h;document.querySelectorAll('.sideitem').forEach(x=>x.onclick=()=>select(x.dataset.base));$('inventory-count').textContent=current.rows.length}
function renderTable(){let h=`<table class="grid"><thead><tr><th style="width:60px">${esc(t('onset'))}</th><th style="width:105px">${esc(t('class'))}</th><th style="width:180px">${esc(t('decision'))}</th><th style="width:90px">${esc(t('confidence'))}</th><th>${esc(t('acoustic'))}</th><th>${esc(t('synthesis'))}</th></tr></thead><tbody>`;for(const r of current.rows)h+=`<tr data-base="${esc(r.base_unit)}" class="${r.base_unit===selected?'selected':''}"><td class="symbol">${esc(r.base_unit)}</td><td>${esc(term('class_name',r.class_name))}</td><td><span class="decision-mark ${esc(r.decision)}">${esc(term('decision',r.decision))}</span></td><td>${esc(term('confidence',r.confidence))}</td><td>${esc(term('acoustic',r.acoustic_evidence))}<div class="rawcode">${esc(r.acoustic_evidence)}</div></td><td>${esc(term('synthesis',r.synthesis_evidence))}<div class="rawcode">${esc(r.synthesis_evidence)}</div></td></tr>`;h+='</tbody></table>';$('table-wrap').innerHTML=h;document.querySelectorAll('.grid tbody tr').forEach(x=>x.onclick=()=>select(x.dataset.base));$('matrix-count').textContent=current.rows.length}
function contextLabel(x){if(lang==='en')return x;const m={plain:'普通语境',rounded:'圆唇语境',front:'前化语境',other:'其他语境',i_series:'i 系',u_series:'u 系',v_series:'ü 系'};if(m[x])return `${m[x]} / ${x}`;const p=x.split(':');if(p.length===2){const a={internal:'内部',initial:'词首'}[p[0]]||p[0],b=m[p[1]]||p[1];return `${a}:${b} / ${x}`}return x}
function renderGroups(r){return r.groups.map(g=>`<div class="grouprow"><div>${esc(g.id)}</div>${g.contexts.map(c=>`<div class="context">${esc(contextLabel(c))}</div>`).join('')}</div>`).join('')}
function renderGap(r){const g=r.evidence_gap;if(!g)return `<div class="section"><h3>${esc(t('evidence'))}</h3><div class="explain">${esc(t('noGap'))}</div></div>`;const diag=g.diagnostic_items.map(x=>`<div class="diagrow"><div><b>${esc(x.syllable)}</b> · ${esc(contextLabel(x.context_family))} · r${esc(x.replicate)}</div><div class="context">existing=${esc(x.existing_observations)}</div><div class="recline">${esc(x.reclist_line)}</div></div>`).join('');const reasons=g.rationale.map(x=>`<div class="reason">${esc(x)}</div>`).join('');return `<div class="section"><div class="gaphead"><h3 style="margin:0">${esc(t('evidence'))}</h3><span class="priority ${esc(g.priority)}">${esc(term('priority',g.priority))}</span></div><div class="kv" style="margin-top:7px"><div class="k">${esc(t('gap'))}</div><div><div class="value-main">${esc(term('gap',g.gap_type))}</div><div class="value-raw">${esc(g.gap_type)}</div></div><div class="k">${esc(t('next'))}</div><div><div class="value-main action">${esc(term('action',g.recommended_action))}</div><div class="value-raw">${esc(g.recommended_action)}</div></div><div class="k">${esc(t('role'))}</div><div>${esc(g.role_scope||'all')}</div><div class="k">${esc(t('families'))}</div><div>${g.context_families.map(contextLabel).map(esc).join(', ')||'—'}</div></div>${diag?`<h3 style="margin-top:10px">${esc(t('diagnostics'))}</h3><div class="diag">${diag}</div>`:''}<h3 style="margin-top:10px">${esc(t('reason'))}</h3>${reasons}</div>`}
function renderInspector(){const r=current.rows.find(x=>x.base_unit===selected);if(!r){$('inspector').innerHTML=`<div class="inspector-empty">${esc(t('idleInspector'))}</div>`;return}const ex=EXPLAIN[r.decision]?(lang==='en'?EXPLAIN[r.decision][0]:EXPLAIN[r.decision][1]):r.decision;$('inspector').innerHTML=`<div class="inspector-inner"><div class="phoneme-title"><span class="big">${esc(r.base_unit)}</span><span class="type">${esc(term('class_name',r.class_name))} / ${esc(r.class_name)}</span></div><div class="section"><h3>${esc(t('interpretation'))}</h3><div class="explain">${esc(ex)}</div><div class="caution">${esc(t('caution'))}</div></div><div class="section"><div class="kv"><div class="k">${esc(t('decision'))}</div><div><div class="value-main">${esc(term('decision',r.decision))}</div><div class="value-raw">${esc(r.decision)}</div></div><div class="k">${esc(t('confidence'))}</div><div>${esc(term('confidence',r.confidence))}</div><div class="k">${esc(t('acoustic'))}</div><div><div class="value-main">${esc(term('acoustic',r.acoustic_evidence))}</div><div class="value-raw">${esc(r.acoustic_evidence)}</div></div><div class="k">${esc(t('synthesis'))}</div><div><div class="value-main">${esc(term('synthesis',r.synthesis_evidence))}</div><div class="value-raw">${esc(r.synthesis_evidence)}</div></div></div></div>${renderGap(r)}<div class="section"><h3>${esc(t('groups'))}</h3><div class="groups">${renderGroups(r)}</div></div><div class="section"><h3>${esc(t('notes'))}</h3><pre class="notes">${esc(r.notes.join('\n'))}</pre></div></div>`}
function renderStats(){const s=current.summary;$('onsets').textContent=s.onsets;$('units').textContent=s.synthesis_units;$('unresolved').textContent=s.unresolved;$('supplement-count').textContent=s.supplement_items;$('unsupported').textContent=s.unsupported}
function renderAll(){renderSidebar();renderTable();renderInspector();renderStats()}function select(base){selected=base;renderSidebar();renderTable();renderInspector()}
async function browse(){setStatus(t('opening'));try{const r=await fetch('/api/pick-folder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lang})}),d=await r.json();if(!r.ok)throw Error(d.error||t('failed'));if(d.path)$('voicebank').value=d.path;setStatus(d.path?t('picked'):t('canceled'))}catch(e){setStatus(e.message,true)}}
async function analyze(){const path=$('voicebank').value.trim();if(!path){setStatus(t('choose'),true);return}const b=$('analyze');b.disabled=true;b.innerHTML=`<span class="spinner"></span>${esc(t('analyzing'))}`;$('browse').disabled=true;setStatus(t('running'));try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})}),d=await r.json();if(!r.ok)throw Error(d.error||t('failed'));current=d;selected=d.rows[0]?.base_unit||null;['profile','inventory','supplement'].forEach(id=>$(id).classList.remove('disabled'));renderAll();setStatus(t('done')(d.summary.onsets,d.summary.synthesis_units))}catch(e){setStatus(e.message,true)}finally{b.disabled=false;b.textContent=t('analyze');$('browse').disabled=false}}
$('lang-zh').onclick=()=>{lang='zh';applyLang()};$('lang-en').onclick=()=>{lang='en';applyLang()};$('browse').onclick=browse;$('analyze').onclick=analyze;$('voicebank').addEventListener('keydown',e=>{if(e.key==='Enter')analyze()});applyLang();
</script>
</body>
</html>
"""
